---
apiVersion: bitnami.com/v1alpha1
kind: SealedSecret
metadata:
  name: anytls-config
  namespace: proxy
spec:
  encryptedData:
    config.json: AgAl24xvXWRRMZccDLzVaDt2pb4Wida3wgPb+vxMTyi3eKEnhcFSRmrbnFzRCZn3X3b0bDSzBlpraR3rFpMWdjcsumsrG8/opW21r+j76G7ii47grVxvaUSOWMPdIJdgu6Ww/k2XHPta0Sho8d1NZMv6A9hleQWri15J7xXKPWxcesS6gJKfC08GrTdjKEpGbD5EqXEb3NM0BqYsxxDiZvmwuyqi6D9G7dk0D+9kgy4uXq+ECCl9vbfAcGBGQt7hO2G2+poIIf/Dym4OMVEImuiJ5pYE16SG2EGFUk1cdS92hADwFRibcuZ6I/ZuA9TU9bfD/Cwp3p5n4Mr4ieuQti/axChd5+TodTfVgtveZnPkkWC4vgV9JNw5OUAhKM1cXoMZkJP6VISCKO3yy+ygJerGuglWGc+Z9HVFXhovOSbtmnpmdPOma3peVl4nTefM+60/vpRHrCaQBi0Gz2UgqOclZ6ZWP6DtWo/+jGQg46mRg30lT7jzL+1qPyaS8gOCm6LeSe1WvCG5af4o4XpxPFzYRw7dniYzBw3m0t9xFOAxh4HRweP1/4m972BVQMBY6+VZkA0xnEIvvT1OLVs5dCWDBAY58MhUsAMCwN0t13uA3Vpv2q8BbTHRvGoaOWKW0qNrKyMWj/mE5BoTaWvSCGv2hEwAN34fsIwvI6msp184lGXVirrQT+WxV+9M/VKOHJ1YcN0Q8ZiygdF79NiVQ8tcmToVUctoi/NOO34RBPLcqXnJRX5v0NeXD+UK+rOlN/bToiEhrnCXhR4HLGl0xAgzurKGm5j+rraJtFQVoMt7pndYpZa83RCHXYKK6f2CVHfXaqFKy82bxfpYnRkSKDhOhlwyRVTSAeCwr5EaGkLbfMCnf/A4hW0Tad63qL8fgVXJV8fl2dgHtrS2rcM+vud3WL7nE56l6w+GZvcYzLxZ18QwibVgkMVKJqtrzPQC4REc0sFoWFnkcRgPWuGz7m3vA8J9hExuSA6XEIgxj6CJ+KyEXRV7+Iz2kRCb5JcYqi+QqOib1mjA1z9dBD2i+Y/AFerqPZUHXtBtEul5Po35SgJRkWurF04BNRbkPcz9j3JLhqIjXLjyKlWHdBM3RRdZi4r2LDsCtHdKKw9ND7wG2kVr22OoiE0CS9YZtM6hUUn7deqln8kM5QqQFZ8nCZPu3ErTQAS8+9OWhua7/APSv/5K2KJyTGUkEWbrKBgZAXcFTDIbCOueWG+QpQ==
  template:
    metadata:
      name: anytls-config
      namespace: proxy
