---
apiVersion: bitnami.com/v1alpha1
kind: SealedSecret
metadata:
  name: hy2-config
  namespace: proxy
spec:
  encryptedData:
    config.json: AgDNMHKgIF6w/5tBrDU0y0a7MN351zM3wQCNSJxnY6FkDTeMBQMcXDUQyI+fMvVad/U7RRTd47buTlyVXrJLv3c2c1znvYKQ65dwVkss5LGrGN68cpjL3PrlA1y+bVxEmRnZpUstAqMHCwSNZYfmm6TRI7plym6yzK+vBhexkbk7B6cVDCkUnyXc6Hy8+Q3VkFQReoxTBJ+rncQUb0Xb3CRJpaRwMuov7ajTgNi+qZUEpXtlDO9hfIwDOmG/2lQyOEAlS7NpIXZFaPK94ogzfkgNUH2frqRSCNt5jKen7KD784yXl6hYxL9U1vXZAfw9aiVy8l2ptHWuo5eeWhW/oEo2NGy6U//1hdKfCIrA5gFdXW5P3y7uSuIzlyw3kHMatChAUqZOLKwuvYfyDnA4uPWq7Xk2BAAt597vzzpRCYphP9J3maIrFPOYqA3GTwlkDTCN7j7dCBTS4xf4pFhexMq51Rfjqi5Q6yn95a1eAhmIUvxoc9spulu+k/SVGne+BqKmsvFnSlPMJVKCcxL56w6i9D69VQNp3m0a+Afji8HM6ruIk6s4gon9tMa6pN1OWKrEWQ4vz/VJU2jP7i6RAmxzMPV0OgJwzpRzDTQyUtfEguNDj0NBuZvm0e02EOhmbm5c9kKJD7LYLNYVbQTZLQBiHyUiZB+RxrbBc0/ty4g+UeUgNZaOed8YwLht1RfloJwOA5pbsUDsYJR+jNXnfLQEvZKS+yM2HrA5BNqdLvr8KjVstdztCGK0DJmucHLIzuDiEf/Xobw+HxKdh5RTVSZB27Ua2TNjxNJ+R2/3FT67fQ7QAIgi0HkzN0FeIXdEA9ZcBvjYCeC7qn7mRv0zzYNzn/9VqmHkDRUkQq+mpUNgwf+UOxKmxH8pObh8QXjlsySN5z7WC6E+BGO2A1urXqt32DdQ63K2Ry7jErXxqcUurwZSE05n6E5IBO0lyGDjmARKMPM7VB2CvX6UxuWjhH+mgkg2JbR88WbO/u/PVxzSvOUELiIc5WEUj5qt8ZdPc2IrahAW3rezJB6oFR9IlFDV4K9giZ/4rtcYYcC6O9JuOY5pVWCDJY5LZgsNjcrX5Oj55VhN067/8DjdP5q+8pPYE8jJ34/0NUOxXrSTEX8kKJtIEyN0urH5Z7pqnZ7+A0Y/3A5eiO2xvNE8lEd6+aTJv6xjbIM27kyNgYR58EufFmAXbO5xVOS4tEnK5yz6j6gM
  template:
    metadata:
      name: hy2-config
      namespace: proxy
