---
apiVersion: bitnami.com/v1alpha1
kind: SealedSecret
metadata:
  name: r2-creds
  namespace: gitea
spec:
  encryptedData:
    access-key: AgBtAfXehhDSCgPgzRbd/fUZKp2405Xau4Ixjvkv4r5N1jaUDhZoSxHxoJYromJlHPB+YTQVFWevn+8+pv0e8sJeo85wimT36xDpaeb+avC2pgJDTlD7zI4DLrGWqs4lLBtcArW/aM1wOHq6jL8dD2nv7BZF5peNQzCvfv3ssGjgd6vsJeR841cX8Rxx14vUzLV3XRHDGtgly9miHYCkMARheD7N4Qj+8FIhO3o8r0c0KgaKhjR6JrfqfabRYSZiNZ2Q58eO6JYTtCh4vUsj4L554lgi8MmGRozV5movIvt9u6NIZNjXRNdDHLQ0fJbFJunN8y0TJuPHoFd5wWxzrOSWzt2LR0ZkrZwzZksnmjbwjpgN3+rKD2iU65KwgkdH/auhDZESjs7earMQCxsWY0JS80SwEK3D7tPxHSsiIq+0gzRqjaNc+Eyd25im1AgjIjE6sG7JbpK7aXZQG2MScnA32WSMsA5omF9lAx6YMiBCMB7UMHjf9wVpgZjtZV+2n14vEc8kQb64vzSzxwBcIqnt727BuKdmHFyE/0VsIIhde6SDmbq4dBA11BbfCrcqEUjY1re4BJV2TYtfz+YcAZ7sy1rRb+ujFhWY0n5LSG1fYDV92+wQBVP5b476huUC7o6nG72JIhuAVQa+XCVoi29ZKH478EWh8N51yPXF0s7JZW0ln2mAmgYxspp1Y4SX6pfYVbhImBDElkyjOFoU6zuEHHBagZjChV2zeS+u0V8SZA==
    secret-key: AgALtMuMwShVhfCY72bjYcwmmGtU3tmeOL0+cCRwqw046EIqS1vDWh3p+5bhSaQqvSSXhzpg4VLS7J1ayOg2oJNj9GOcaiYDoeddWXV5RFrTZcF/AiXHbwp7LLeumZ09PlhEIzQaVjXtw9UKgQhLblfW3m7oecOlpzS4Dz+aAq6Lt/6JtbBBJ3Z+7/7mmygORU7TFaSsjDEJrbwp7fFxrnL9UYM3TncElwuzcyEHgtY3Vc0aRxiLmiHQVY6MUlYdFWrMIkxIkAkQPnIxrgv4XmevbEzQXdpWEIvpN4LtdKz6Tjyu11L6sYJ+lcRlf1YJtgi2VGOoHlGc7bOA+VIYzyNAnDabayJoQejHgseo6QEnE5K07N8g2Bdzs6Mdye1uHaq+yVJtHCeKJaB+bWIeNuuWfMHNTr5r8GCfn2gbQvhhMXYzzb5gTDhf+sxdxKdYMcIKYxSRTtljVvnikpDkQLk9NaBzUhjb8Hyg4n1uWd2Am67WPp3C80Vk9Sulr/McQNsBgF2cZCw2pciJsJ/e0YPNYfInRBW9D9Glw/kQCRxcpe3d7gfjPO2Blotjfjth7hLLLaltepPP/wWI1gAcvZqlQqNltaJpVF+4+no/COZIZaltbJY+cXCW80FRWgCRjkruS9Iii2cvq+Eh2I3xcL8fL3CVQrhYPBbiSf/MOxzoCUCAEAk8aDlh4JE2w1l/AqE+5DatwK4xxRZ0Z2DkdosAWzYomC8O8UH1nIPUBXlUUPSQxlBdki7F64F/PNC3RFQQdfkZH8nFAFZCq821xtsK
  template:
    metadata:
      name: r2-creds
      namespace: gitea
