apiVersion: cert-manager.io/v1
kind: Certificate
metadata: {name: lee, namespace: lee}
spec:
  secretName: lee-tls
  issuerRef: {name: letsencrypt-prod, kind: ClusterIssuer}
  dnsNames: ["lee.k4s.live"]
