---
apiVersion: bitnami.com/v1alpha1
kind: SealedSecret
metadata:
  name: grafana-admin
  namespace: monitoring
spec:
  encryptedData:
    admin-password: AgB8skWs1KPhtdbdq6aJo8pAgHHcdd0KaM3GxVxMPsOCs+6qXjG/2znBYp35f0I7cGfVRkRo8IwU9bVnM/lkoNiaVxrqWcIsyONnNNxvymXvbY19t/LvoZBDj9YWlK6/MEcO1ltT78LCdBNVHF8zAgY7soX0Q1GP9LZanvdaiSuNNoqGw2jp5CBbD+QEG5HYCCm0X6mLFfq2fMhXHTEe41+8su01qEdO6nSB2Y/rTHBtS1/OarvKh7iUXCsvqGuG9BIzvy0/sc1CRpGr7H1mA1suC0nzpfEpvcDGhcgqAf6KO/2Nsn8zCfg/jC6HwdjmW3wIC4CqUihm5nlUYGqk6yb8jD50hGsl7nr0Ypqdg5vhvSgVCC0jdiVxkq0Hc688Qlz45t+lLx8BQtklldWzJLAIdwiOj7VtG2P0wSyRsVRUbzQvx/HoHkx1gO4oHFx5/SElCGhGGTRg7nFKHrgPKmgweZbKdtFnRJUTSmGMvSm7OGBw8yye5LweUKXrA6JcW1kIq/Ne11v+ELtdKFyubiBvOBjO1CoeTtyfITSv6zvZfXbt4uxR8ibt4JAvgitpk2rB77P0F8hcvgrRtohLPCKBfcKa6wOgukRYhbZ2GCdRobPJpso91xih7xizxMoOpv1Sgpt9m5bzgGbYK0x8M6UBw7rLqBWdq/NjAEs/Aez5RtizlYS8FFXqP7WrJWGNzDtlyHMGm+b/SYf5yQ/kk6M=
    admin-user: AgAPg+qszbbJV/KZIBzjAAtXosnqtDG296pNQ6l5pKTJsItzEivFb0eOx7By9Fc0Ou+/YvAK7JSZ8BjCNGoz84fnI0vuy6DIBtXfgLxVMLcD6EU6ACB7D17y7XirDRmR1iWvBqUobDsr01+xlJTvmNVhmTocDnuOUxpxz+vbN0hJp6JdlKNAT/yq+mrUMgMsNZjVOqPrdjZxsghC2pfiYKTrYr9AAvR/aEG1T4d5xaLblsgvkTls4Ug0dPShDF25uCLWX6Y0EV7XIZBVZXEKWxtvCRvRk0fJH+9Jmlft15kiFci/353drL3zCYnE83W1ed1mon9TbBj3GBOrTsN44EVjPq+HawHnB0j89FU9oFNod4EHhDC0GfUCJmKEb9rLGACk8jbYo7x65cccWP2eS5vsjNpeQj7U109gjdOEKrVi3x+HKJhCcDtPAfnkhkSwQKHLqLpbjkxhDSZ3M/2HYaeRui/bz9MDfaA5uLHza5Zu+imGgmjgm12QbVWpusRKeK+k4zd1tyecBUAiMAkcI3rFfpZIc4vcN8tuhZwxhhrMW8tiiNee9gvx9xL8Jd6n4BvK8usuZtkEYlEZIAjw/7TfvDC6l+WVwEXyqdO+fB/uO/ZrQrgyUUX1ylFVe99fxwTDafxanb8RvfhqH3lD2KkVjnTAapG0yfenYHUot7B6RP2WGMoUy/HKpu0YGUcA1OTlRlMagQ==
  template:
    metadata:
      name: grafana-admin
      namespace: monitoring
