---
apiVersion: bitnami.com/v1alpha1
kind: SealedSecret
metadata:
  name: r2-creds
  namespace: kube-system
spec:
  encryptedData:
    access-key: AgBjyDz2J+yM+EaDcDUC0rSL1ghqmsyKlou/35Vd50Z0dOkTFmfgGWJRK7xEiwXGiRK8w/rHLfgkg+O8EkyMZWBkC+j6BD1isE7kzOgtQNQUX1WmXcMYpf7O3yGDFPEhzj+Fd8C5htPnt9LTmjniIuoxlxiqpTQMEInRpfQIta3mSLfFHcf4JI0jOG9UXf5Bd61DBg3QDtZmCIfGlgLKEp/bd6ZqGg7TpcBu7jbnCFo8qZhESbmYoVSMq5x8htN/yGvPQxfboKXwnBm65kecLpJaxG1XO+O4PhguhUyYm8HM1h/EJslFNYqWSPAvUssGVdSwTgYC09eQc9EksUQDIX3x9fRJxSgDfvPfYDjNXUZ0PjyzcCU1gYcqkO7Hywyr/MKsb7hel73RDBVBl/HyVPFseE8yzIxSTj4287glumIWwQW1qdabSkHi0Mw302OnnrxWARlAbjDkh8sDleFucNnEQgtXxlaZiSqrK8mr1ejT2qmiMrdS7vYoNhFe+igfC8MeBwPICyRaGsLcpNHICvS906V+AXYlrYxIVgamGuDEJ52CS4u8Z80c4wva58f7dF+I57uTogvHF9aCfsycQdUNSLPvvhrnLSK+YU+V2eGObwHKzC6VEfLPtf8QDSZmInL1nHc4fVXza9BHzJLFSzRDYXjM+5MuK4I+WXHELYELr3io8Hw/KUSp0akCz1t9dCXxvMzKTh8fgKxXB5CFrHaupx65TeH/BHbBUSzVBvD+3g==
    secret-key: AgDNUCEuub/A3QOnxdw0qce6Igv29sZ0BlGLVTa2ZTa5uzLQ1sEMbNARFqvCErq0eley4h/byjDJ8cC5f2iEoCliuvUftrMTWarPp9AiqUhRsf+0OXh/EIsbSyTyjCI8g6Sap85R2fZ1Ds3CHZrkbctLhdCbLiuyoX7pZn+ojQmMp5kRN3/2XpXeF5UMMaf9+K2QGqaPXWgvQ3bLBvo7OMi5B7jEvDm0VNme5CdZuAQ+zey2BXDNaBlUivrDnLNC+/534glSI5Y9nJSBXmiCa5KgBqXcTxVtRCBmVxwezXvRsIg92aGGY9UVSYeRJBWT9FZhjoO6n0q1dRapaqqnBrFjDj8unhnN4lh5ZzBrKB30Z8W+5lvNpMHk+rdgWtldstFSvTMc7nP5QhE6LW1Oa7dDsEuHypIWPonv/P2Hy22LdEmH33qAb6dimjqJNmPtyOfe4I7+KjB1gW10fP8VrX/C6WfyMrlgdk2ifLFP37oTWpBCdeWnxfZovxC38/aqbEmUGZ9MECw5+gDz63JZEBxcXv7UUIrhwabZYvweezPFrR4U4wQP6v6/Ou6Seln4Lc6vXCuiP3SXMgJZXHr8woSHHGamywf7+nLMJL3OLHP5QqR4Cj9XfjreWxKDfknvVjxj4WbATL8Lv/FB+Cw0zcyq7RUcYJrYR1OoADYHUmGwpM9nKu6dCd9R3CRyfyWMuoMqYrR+6lK7MPuzJcNCrjyb7oeXw5vltk8Nu/rVZrMC3JnO4FGNGW102GgEBFSyKloFhYR31fBj+ZHmoyXNoOwN
  template:
    metadata:
      name: r2-creds
      namespace: kube-system
